// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v6.33.1
// source: api.proto

/* eslint-disable */

export const protobufPackage = "api";

/** Player summary for lists */
export interface PlayerListItem {
  rank: number;
  playerId: number;
  /**
   * cuescore_id is optional in Rust model, mapped to int64.
   * In proto3, optional fields are explicit.
   */
  cuescoreId?: number | undefined;
  name: string;
  rating: number;
  gamesPlayed: number;
  /** string for JSON compatibility ("established", etc.) */
  confidenceLevel: string;
  matchesPlayed: number;
}

/** Detailed player view */
export interface PlayerDetail {
  playerId: number;
  cuescoreId?: number | undefined;
  name: string;
  cuescoreProfileUrl: string;
  rating: number;
  gamesPlayed: number;
  confidenceLevel: string;
  mlRating: number;
  starterWeight: number;
  mlWeight: number;
  effectiveGames: number;
  /** Date string */
  lastPlayed?: string | undefined;
  matchesPlayed: number;
}

/** Paginated list response */
export interface PlayerListResponse {
  items: PlayerListItem[];
  total: number;
  page: number;
  pageSize: number;
}

export interface HeadToHeadMatch {
  date: string;
  tournamentName: string;
  player1Wins: number;
  player2Wins: number;
}

export interface HeadToHeadStats {
  totalMatches: number;
  player1MatchWins: number;
  player2MatchWins: number;
  totalFrames: number;
  player1FrameWins: number;
  player2FrameWins: number;
}

export interface HeadToHeadResponse {
  player1: PlayerDetail | undefined;
  player2: PlayerDetail | undefined;
  probabilityP1Wins: number;
  matches: HeadToHeadMatch[];
  stats: HeadToHeadStats | undefined;
}
